# release data downloaded to disk
data_root: /home/nuo/vlm_proj/scanpp_samp/scannetpp_3_scenes/data
scene_list_file: /home/nuo/vlm_proj/tmp.txt

filter_scenes: ["7b6477cb95"]

# image type - iphone or dslr
image_type: dslr

no_log: true

# subsample images 
subsample_factor: 1

# downsample images and rasterize
image_downsample_factor: 3

rasterout_dir: /home/nuo/vlm_proj/temp_rasterize

limit_images: None

wandb_group: null
wandb_notes: null

batch_size: 1
limit_batches: null
skip_existing: true