# python -m semantic.prep.rasterize
# release data downloaded to disk
data_root: ../Journey9ni_raw_data_part/scannetpp/data
scene_list_file: ../QA_scannetpp/sc_name.txt

filter_scenes: []

# image type - iphone or dslr
image_type: dslr

no_log: true

# subsample images 
subsample_factor: 1

# downsample images and rasterize
image_downsample_factor: 4

rasterout_dir: ../temp_rasterize

limit_images: None

wandb_group: null
wandb_notes: null

batch_size: 4
limit_batches: null
skip_existing: false